apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Workflow

on:
  push:
    branches:
      - '**'

jobs:
  build-and-publsh:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world2"

      - name: checkout code
        uses: cloudbees-io/checkout@v1

      - name: build
        uses: docker://maven:3.9.6-eclipse-temurin-17
        shell: sh
        run: |
          mvn clean install

      # - name: Setup Dockerhub container registry
      #   uses: cloudbees-io/configure-oci-credentials@v1
      #   with:
      #     registry: index.docker.io # or docker.io
      #     username: ${{ vars.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_PASSWORD }}
      # - name: Push image to the configured OCI Registry
      #   uses: cloudbees-io/kaniko@v1
      #   with:
      #     destination: ${{ vars.DOCKERHUB_USERNAME }}/sample-go-app:1.0.9
  
