apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Workflow

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    

jobs:
  build-and-publsh:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1

      - name: Build JAR
        uses: docker://maven:3.9.6-eclipse-temurin-17
        shell: sh
        run: |
          mvn clean install

      - name: Configure container registry
        uses: cloudbees-io/configure-oci-credentials@v1
        with:
          registry: index.docker.io # or docker.io
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and publish container image
        uses: cloudbees-io/kaniko@v1
        with:
          destination: ${{ vars.DOCKERHUB_USERNAME }}/quickstart-java-app:${{ cloudbees.version }}

  
